filter:
    excluded_paths: [vendor/*]
    paths: [src/*, tests/*]

before_commands:
    - "composer install --prefer-source"

tools:
    php_code_coverage:
        test_command: phpunit -c phpunit.xml.dist
    php_cpd:
        excluded_dirs: [vendor/*]
    php_code_sniffer:
        config:
            standard: PSR2
    php_pdepend:
        excluded_dirs: [vendor/*]
    php_analyzer: true