language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - "composer selfupdate"
  - "composer --version"
  - "composer install --prefer-dist --verbose"
  - "composer install --dev"

script:
  - "phpunit"